<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>

		<!-- ADD THIS LINE TO ENABLE C# 13/14 PARTIAL PROPERTIES -->
		<LangVersion>preview</LangVersion>

		<RootNamespace>Winmozhi.UI</RootNamespace>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<NoWarn>NETSDK1206</NoWarn>
		<NoWarn>NETSDK1206;CA1416</NoWarn>
		<WindowsPackageType>MSIX</WindowsPackageType>

		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<PublishReadyToRun>False</PublishReadyToRun>
		<TieredCompilation>true</TieredCompilation>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<GenerateTestArtifacts>False</GenerateTestArtifacts>
		<AppxBundle>Never</AppxBundle>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Assets\BadgeLogo.scale-100.png" />
	  <None Remove="Assets\BadgeLogo.scale-125.png" />
	  <None Remove="Assets\BadgeLogo.scale-150.png" />
	  <None Remove="Assets\BadgeLogo.scale-200.png" />
	  <None Remove="Assets\BadgeLogo.scale-400.png" />
	  <None Remove="Assets\LargeTile.scale-100.png" />
	  <None Remove="Assets\LargeTile.scale-125.png" />
	  <None Remove="Assets\LargeTile.scale-150.png" />
	  <None Remove="Assets\LargeTile.scale-200.png" />
	  <None Remove="Assets\LargeTile.scale-400.png" />
	  <None Remove="Assets\SmallTile.scale-100.png" />
	  <None Remove="Assets\SmallTile.scale-125.png" />
	  <None Remove="Assets\SmallTile.scale-150.png" />
	  <None Remove="Assets\SmallTile.scale-200.png" />
	  <None Remove="Assets\SmallTile.scale-400.png" />
	  <None Remove="Assets\SplashScreen.scale-100.png" />
	  <None Remove="Assets\SplashScreen.scale-125.png" />
	  <None Remove="Assets\SplashScreen.scale-150.png" />
	  <None Remove="Assets\SplashScreen.scale-200.png" />
	  <None Remove="Assets\SplashScreen.scale-400.png" />
	  <None Remove="Assets\Square150x150Logo.scale-100.png" />
	  <None Remove="Assets\Square150x150Logo.scale-125.png" />
	  <None Remove="Assets\Square150x150Logo.scale-150.png" />
	  <None Remove="Assets\Square150x150Logo.scale-200.png" />
	  <None Remove="Assets\Square150x150Logo.scale-400.png" />
	  <None Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
	  <None Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
	  <None Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
	  <None Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
	  <None Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
	  <None Remove="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" />
	  <None Remove="Assets\Square44x44Logo.altform-unplated_targetsize-24.png" />
	  <None Remove="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" />
	  <None Remove="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" />
	  <None Remove="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" />
	  <None Remove="Assets\Square44x44Logo.scale-100.png" />
	  <None Remove="Assets\Square44x44Logo.scale-125.png" />
	  <None Remove="Assets\Square44x44Logo.scale-150.png" />
	  <None Remove="Assets\Square44x44Logo.scale-200.png" />
	  <None Remove="Assets\Square44x44Logo.scale-400.png" />
	  <None Remove="Assets\Square44x44Logo.targetsize-16.png" />
	  <None Remove="Assets\Square44x44Logo.targetsize-24.png" />
	  <None Remove="Assets\Square44x44Logo.targetsize-256.png" />
	  <None Remove="Assets\Square44x44Logo.targetsize-32.png" />
	  <None Remove="Assets\Square44x44Logo.targetsize-48.png" />
	  <None Remove="Assets\StoreLogo.scale-100.png" />
	  <None Remove="Assets\StoreLogo.scale-125.png" />
	  <None Remove="Assets\StoreLogo.scale-150.png" />
	  <None Remove="Assets\StoreLogo.scale-200.png" />
	  <None Remove="Assets\StoreLogo.scale-400.png" />
	  <None Remove="Assets\Wide310x150Logo.scale-100.png" />
	  <None Remove="Assets\Wide310x150Logo.scale-125.png" />
	  <None Remove="Assets\Wide310x150Logo.scale-150.png" />
	  <None Remove="Assets\Wide310x150Logo.scale-200.png" />
	  <None Remove="Assets\Wide310x150Logo.scale-400.png" />
	  <None Remove="Views\PopupView.xaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.1.3" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="H.NotifyIcon.WinUI" Version="2.1.4" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Winmozhi.Core\Winmozhi.Core.csproj" />
		<ProjectReference Include="..\Winmozhi.Hooks\Winmozhi.Hooks.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Views\SettingsWindow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Views\PopupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Converters\" />
	</ItemGroup>
</Project>